-- CREATE TABLE user (
-- `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
--  name varchar(35),
--  PHONE varchar(35)
-- );

-- CREATE TABLE system_user COMMENT ('用户信息')(
--     `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT ('用户ID'),
--     `username` VARCHAR(50) NOT NULL COMMENT ('账号'),
--     `password` VARCHAR(50) NOT NULL COMMENT ('密码'),
--     `name` VARCHAR(50) NOT NULL COMMENT ('姓名'),
--     `update_time` DATETIME COMMENT ('更新时间'),
--     `create_time` DATETIME COMMENT ('创建时间')
-- );

INSERT INTO `system_user`(`username`,`password`,`name`,`update_time`,`create_time`) VALUES ('xutu', '$2a$10$K4jxeDMsZBDBSxvulmfemeRFC7clo90Hmr5dMiQOcGmVs2KbJn2wm', '徐图', now(), now());


-- CREATE CACHED TABLE SYSTEM_RESOURCE COMMENT STRINGDECODE('系统资源信息')(
--     ID INT NOT NULL  AUTO_INCREMENT,
--     PID INT NOT NULL COMMENT STRINGDECODE('父级ID'),
--     NAME VARCHAR(20) NOT NULL COMMENT STRINGDECODE('资源名称'),
--     URL VARCHAR(150) NOT NULL COMMENT STRINGDECODE('资源链接'),
--     TYPE TINYINT NOT NULL COMMENT STRINGDECODE('资源类型 1：菜单 2：按钮'),
--     SORT INT NOT NULL COMMENT STRINGDECODE('排序标识'),
--     UPDATE_TIME DATETIME NOT NULL COMMENT STRINGDECODE('更新时间'),
--     CREATE_TIME DATETIME NOT NULL COMMENT STRINGDECODE('创建时间'),
--     PRIMARY KEY (`id`)
-- )
--
-- CREATE CACHED TABLE PUBLIC.SYSTEM_ROLE COMMENT STRINGDECODE('角色信息')(
--     ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT STRINGDECODE('角色ID'),
--     ROLE_NAME VARCHAR(50) NOT NULL COMMENT STRINGDECODE('角色名称'),
--     ROLE_TAG VARCHAR(20) COMMENT STRINGDECODE('角色标识'),
--     UPDATE_TIME DATETIME COMMENT STRINGDECODE('更新时间'),
--     CREATE_TIME DATETIME COMMENT STRINGDECODE('创建时间')
-- )
--

--
